# Generated by Django 6.0.2 on 2026-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro Trader'), ('elite', 'Elite')], default='free', max_length=10),
        ),
    ]
